name: Compile examples

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run examples
        run: |
          cd examples
          for example in $(ls *.rs); do
            echo "Building and running example: $example"
            cargo run --example $example
          done
