name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Libraries
      run: |
        sudo apt update
        sudo apt install -y libasound2-dev
        sudo apt-get install libudev-dev
    - name: Build
      run: cargo build --verbose
    - name: Build and run examples
      run: |
        cd examples
          for example in $(find . -type f -name '*.rs'); do
            example_name=$(basename "$example" .rs)
            echo "Building and running example: $example_name"
            cargo run --example "$example_name"
          done

